# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- release
- devel

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
